version: 0.0.0.0

dependencies:
  - base

ghc-options:
  - -Wall
  - -Wno-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -fdefer-typed-holes
    dependencies:
      - hspec
      - hspec-discover

executables:
  fhi:
    main: fhi.hs
    source-dirs:
      - exe
      - src
